import io
import json
from pathlib import Path

import joblib
import pandas as pd
import streamlit as st

BASE_DIR = Path(__file__).resolve().parent
MODELS_DIR = BASE_DIR / "models"

MODEL_FILES = {
    "Random Forest": "random_forest_model.joblib",
    "Logistic Regression": "logistic_regression_model.joblib",
}
LABELS = {0: "Human-written", 1: "AI-generated"}
AI_CLASS = 1

st.set_page_config(page_title="AI Tweet Detection", layout="wide")


# ---------------------------------------------------------------- data loading

@st.cache_resource(show_spinner="Loading model...")
def load_model(name):
    """One model per call, not both. Loading the forest costs ~150ms and there's
    no reason to pay it for a session that only ever touches logistic regression."""
    path = MODELS_DIR / MODEL_FILES[name]
    if not path.exists():
        return None
    return joblib.load(path)


@st.cache_data
def load_json(path):
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


@st.cache_data
def load_results():
    path = BASE_DIR / "model_results.csv"
    if not path.exists():
        return None
    return pd.read_csv(path).sort_values("F1-score", ascending=False)


results = load_results()
confusion_matrices = load_json(BASE_DIR / "confusion_matrices.json")
# Precomputed at training time. Reading the raw 5.8 MB csv here just to count
# rows added about a second to every cold start for three numbers and ten rows.
summary = load_json(BASE_DIR / "dataset_summary.json")

if results is None or confusion_matrices is None or summary is None:
    st.error("Missing model artifacts. Run `python train_models.py` first.")
    st.stop()


# ------------------------------------------------------------------- inference

def ai_probabilities(model, texts):
    """Probability that each text is AI-generated.

    predict() and predict_proba() each re-run the tf-idf transform and walk the
    whole forest, so calling both doubles the work for no reason — the label is
    just this probability against the threshold.
    """
    ai_column = list(model.classes_).index(AI_CLASS)
    return model.predict_proba(texts)[:, ai_column]


@st.cache_data(show_spinner=False)
def score_single(text, model_name):
    model = load_model(model_name)
    return float(ai_probabilities(model, [text])[0])


@st.cache_data(show_spinner="Scoring uploaded file...")
def score_file(file_bytes, model_name):
    """Keyed on the file's bytes, so fiddling with the threshold or switching
    tabs doesn't re-run inference over the whole upload."""
    frame = pd.read_csv(io.BytesIO(file_bytes))
    if "text" not in frame.columns:
        return None
    if frame.empty:
        # TfidfTransformer raises on a zero-row matrix, so bail before sklearn
        # sees it — a header-only csv is a realistic thing to upload by mistake.
        frame["ai_probability"] = pd.Series(dtype="float64")
        return frame

    model = load_model(model_name)
    frame["ai_probability"] = ai_probabilities(
        model, frame["text"].fillna("").astype(str)
    ).round(4)
    return frame


def confidence_note(probability, threshold):
    margin = abs(probability - threshold)
    if margin >= 0.20:
        return "The model is fairly confident here."
    if margin >= 0.05:
        return "This one is close to the cut-off — worth a second look."
    return "This is essentially a coin flip. Don't read much into it."


# ------------------------------------------------------------------------- ui

st.title("AI Tweet Detection")
st.write(
    "Predicts whether a tweet was written by a person or generated by a model. "
    "Treat the output as a flag for review, not as proof."
)

model_name = st.sidebar.selectbox("Model", list(MODEL_FILES))
threshold = st.sidebar.slider(
    "Decision threshold", 0.05, 0.95, 0.50, 0.05,
    help="Anything scoring above this is called AI-generated. Raise it if you "
         "are getting too many false accusations.",
)
st.sidebar.caption(
    "Both models lean towards over-flagging: the forest catches ~90% of AI "
    "tweets but about 1 in 5 of its flags is a human. Nudging the threshold up "
    "trades recall for precision."
)

if load_model(model_name) is None:
    st.error(f"`{MODEL_FILES[model_name]}` is missing. Run `python train_models.py`.")
    st.stop()

tab_predict, tab_compare, tab_dataset = st.tabs(
    ["Try it", "Model comparison", "Dataset"]
)

with tab_predict:
    st.subheader("Single tweet")

    tweet_text = st.text_area(
        "Tweet text", height=140, placeholder="Paste a tweet here..."
    )

    if st.button("Predict", type="primary"):
        if not tweet_text.strip():
            st.warning("Enter some text first.")
        else:
            st.session_state.scored_text = tweet_text

    # Held in session state so the result survives a rerun — changing the model
    # or the threshold now updates the verdict instead of blanking it out.
    scored_text = st.session_state.get("scored_text")
    if scored_text:
        probability = score_single(scored_text, model_name)
        is_ai = probability >= threshold

        left, right = st.columns(2)
        left.metric("Verdict", LABELS[int(is_ai)])
        right.metric("AI probability", f"{probability * 100:.1f}%")

        st.progress(probability)
        st.write(confidence_note(probability, threshold))
        st.caption(
            f"Scored with {model_name} at a {threshold:.2f} threshold. Humans "
            "write AI-sounding tweets and models write convincingly human ones, "
            "so a single verdict is never conclusive."
        )

    st.divider()
    st.subheader("Batch")
    st.write("Upload a CSV with a `text` column.")

    uploaded_file = st.file_uploader("CSV file", type=["csv"], label_visibility="collapsed")

    if uploaded_file is not None:
        scored = score_file(uploaded_file.getvalue(), model_name)

        if scored is None:
            st.error("That file has no `text` column.")
        elif scored.empty:
            st.warning("The file is empty.")
        else:
            # Thresholding is separate from scoring so the slider is instant.
            scored["prediction"] = (scored["ai_probability"] >= threshold).astype(int)
            scored["prediction_label"] = scored["prediction"].map(LABELS)

            flagged = int(scored["prediction"].sum())
            st.write(
                f"Flagged **{flagged:,}** of **{len(scored):,}** rows as "
                f"AI-generated ({flagged / len(scored):.0%})."
            )

            st.dataframe(scored.head(50), hide_index=True)
            if len(scored) > 50:
                st.caption(f"Showing the first 50 rows. The download has all {len(scored):,}.")

            st.download_button(
                "Download predictions",
                scored.to_csv(index=False).encode("utf-8"),
                "ai_tweet_predictions.csv",
                "text/csv",
            )

with tab_compare:
    st.subheader("Test-set results")

    table = results.copy()
    metric_cols = ["Accuracy", "Precision", "Recall", "F1-score"]
    table[metric_cols] = (table[metric_cols] * 100).round(2)

    st.dataframe(
        table,
        hide_index=True,
        column_config={
            col: st.column_config.NumberColumn(col, format="%.2f%%")
            for col in metric_cols
        },
    )

    st.write(
        "BERT wins comfortably because it reads the tweet in context, while both "
        "sklearn models only ever see a bag of tf-idf n-grams. Between the two "
        "baselines it is close to a wash: the forest catches more AI tweets, "
        "logistic regression is more careful about what it accuses."
    )

    st.subheader("Confusion matrix")
    cm_model = st.selectbox("Model", list(MODEL_FILES), key="cm_model")

    matrix = pd.DataFrame(
        confusion_matrices[cm_model],
        index=["Actually human", "Actually AI"],
        columns=["Called human", "Called AI"],
    )
    st.dataframe(matrix)

    false_positives = int(matrix.loc["Actually human", "Called AI"])
    false_negatives = int(matrix.loc["Actually AI", "Called human"])
    st.caption(
        f"{false_positives:,} human tweets wrongly flagged as AI, and "
        f"{false_negatives:,} AI tweets missed. Measured at the default 0.50 "
        "threshold, so the slider won't move these numbers."
    )

with tab_dataset:
    st.subheader("Data")
    st.write(
        "TweepFake and ElectAI merged into one table, with labels normalised to "
        "0 for human and 1 for AI-generated."
    )

    total = summary["total_rows"]
    cols = st.columns(3)
    cols[0].metric("Rows", f"{total:,}")
    cols[1].metric("Human", f"{summary['human_rows']:,}",
                   f"{summary['human_rows'] / total:.0%} of total", delta_color="off")
    cols[2].metric("AI-generated", f"{summary['ai_rows']:,}",
                   f"{summary['ai_rows'] / total:.0%} of total", delta_color="off")

    st.subheader("Rows by source")
    st.dataframe(
        pd.Series(summary["rows_by_source"], name="rows").rename_axis("source")
    )

    st.subheader("Sample rows")
    st.dataframe(pd.DataFrame(summary["sample_rows"]), hide_index=True)

    st.subheader("Where this falls down")
    st.write(
        "The two sources aren't interchangeable — TweepFake is mostly older bot "
        "accounts and ElectAI is election content, so a model trained on the mix "
        "may just be learning topic rather than authorship. Neither set covers "
        "recent models, which is where it would most likely be used. The obvious "
        "next step is holding out one source entirely and training on the other "
        "to see how much of the accuracy actually transfers."
    )
